-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Account_types"
(
    id bigint NOT NULL,
    type_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Account_types_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Accounts"
(
    id bigint NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type_id bigint NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    path_to_profile_photo character varying(255),
    phone character varying(255) COLLATE pg_catalog."default",
    path_to_resume character varying(255),
    CONSTRAINT "Accounts_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Achievements"
(
    account_id bigint NOT NULL,
    total_tests_count bigint NOT NULL DEFAULT 0,
    total_exercises_count bigint NOT NULL DEFAULT 0,
    total_articles_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT "Achievements_pkey" PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS public."Article_Themes"
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Article_Themes_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Articles"
(
    id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rating bigint DEFAULT 0,
    author_id bigint NOT NULL,
    first_paragraph character varying(255) COLLATE pg_catalog."default" NOT NULL,
    path_to_file character varying(255) NOT NULL,
    theme_id bigint NOT NULL,
    CONSTRAINT "Articles_pkey" PRIMARY KEY (id)
);

COMMENT ON COLUMN public."Articles".first_paragraph
    IS 'will be shown as a preview, can be the first paragraph of the file or manually inserted';

CREATE TABLE IF NOT EXISTS public."Person"
(
    account_id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    surname character varying(255) COLLATE pg_catalog."default",
    father_name character varying(255) COLLATE pg_catalog."default",
    dob date,
    CONSTRAINT "Person_pkey" PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS public."Tests"
(
    id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rating bigint DEFAULT 0,
    author_id bigint NOT NULL,
    path_to_file character varying(255) NOT NULL,
    CONSTRAINT "Tests_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Vacancy"
(
    id bigint NOT NULL,
    title bigint NOT NULL,
    path_to_file character varying(255) NOT NULL,
    hire_manager_id bigint NOT NULL,
    publish_date date NOT NULL,
    remove_date date NOT NULL,
    views bigint DEFAULT 0,
    CONSTRAINT "Vacancy_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Accounts"
    ADD CONSTRAINT accounts_type_id_foreign FOREIGN KEY (type_id)
    REFERENCES public."Account_types" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Achievements"
    ADD CONSTRAINT achievements_account_id_foreign FOREIGN KEY (account_id)
    REFERENCES public."Accounts" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "Achievements_pkey"
    ON public."Achievements"(account_id);


ALTER TABLE IF EXISTS public."Articles"
    ADD CONSTRAINT articles_author_id_foreign FOREIGN KEY (author_id)
    REFERENCES public."Accounts" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Articles"
    ADD CONSTRAINT articles_theme_id_foreign FOREIGN KEY (theme_id)
    REFERENCES public."Article_Themes" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Person"
    ADD CONSTRAINT person_account_id_foreign FOREIGN KEY (account_id)
    REFERENCES public."Accounts" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "Person_pkey"
    ON public."Person"(account_id);


ALTER TABLE IF EXISTS public."Tests"
    ADD CONSTRAINT tests_author_id_foreign FOREIGN KEY (author_id)
    REFERENCES public."Accounts" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Vacancy"
    ADD CONSTRAINT vacancy_hire_manager_id_foreign FOREIGN KEY (hire_manager_id)
    REFERENCES public."Accounts" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;